# Generated by Django 5.0.6 on 2024-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=20)),
                ('duracion', models.CharField(max_length=250)),
                ('nota', models.DateField()),
            ],
        ),
    ]
