# Generated by Django 5.0.6 on 2024-07-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoextra',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts'),
        ),
    ]
